### ISSUE TITLE
up to date xtb windows binaries ?

### ISSUE THREAD

**Issue by miroi** [shoubhikraj/xtb-win-build#1]
Hello,

got to your page. Would you please have up-to-date xtb windows binaries,  based on  https://github.com/grimme-lab/xtb/releases/tag/v6.6.1 ?

**Comment by shoubhikraj** [comment]
@miroi Hi, xTB started providing xtb binaries for windows, so I stopped compiling binaries myself. In the releases page you linked there are zip files with windows binaries for xtb. You can get xtb4stda and stda from my compile. Only stda has been updated (but very minor modifications) after my last compile.
